# Generated by nixos-generate-config on this laptop during the owner's
# installation on 2026-10-04 and checked against the mounted filesystems.
# Lenovo Yoga Slim 7 15ILL9 (machine type 83HM, board LNVNB161216), Intel Core
# Ultra 7 258V, 32 GiB. Single SSD: Samsung MZAL81T0HDLB-00BL2, serial
# S77LNF1X652296 (1 TB). The installer created three GPT partitions: a 1 GiB
# ESP, the ext4 root and an 8.8 GiB swap partition
# (UUID 71f0e008-aa66-4607-87b2-029119bb4548, nvme0n1p3). The root is NOT
# encrypted. The host policy uses zram only, so the swap partition is
# deliberately not listed here; it stays on disk, unused, for the owner.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/5054780a-381e-4518-8493-df4929682c36";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/73D4-F5E3";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.npu.enable = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
